export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_USER = "AUTH_USER";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_EVENT = "ADD_EVENT";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS"
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL"
 
export const ADD_EVENT_IMAGE = "ADD_EVENT_IMAGE";
export const ADD_EVENT_IMAGE_SUCCESS = "ADD_EVENT_IMAGE_SUCCESS";
export const ADD_EVENT_IMAGE_FAIL = "ADD_EVENT_IMAGE_FAIL";

export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";

export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";